services:
  create-site:
    image: ${CUSTOM_IMAGE:-frappe/erpnext}:${CUSTOM_TAG:-$ERPNEXT_VERSION}
    pull_policy: ${PULL_POLICY:-always}
    platform: linux/amd64
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: none
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    entrypoint:
      - bash
      - -c
    command:
      - >
        wait-for-it -t 120 db:3306;
        wait-for-it -t 120 redis-cache:6379;
        wait-for-it -t 120 redis-queue:6379;
        export start=`date +%s`;
        until [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".db_host // empty"` ]] && \
          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_cache // empty"` ]] && \
          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_queue // empty"` ]];
        do
          echo "Waiting for sites/common_site_config.json to be created";
          sleep 5;
          if (( `date +%s`-start > 120 )); then
            echo "could not find sites/common_site_config.json with required keys";
            exit 1
          fi
        done;
        echo "sites/common_site_config.json found";
        bench new-site --mariadb-user-host-login-scope='%' --admin-password=admin --db-root-username=root --db-root-password=${DB_PASSWORD} --install-app erpnext --install-app epibus --set-default ${WEB_DOMAIN:-intralogisticsai.online} --force;
        echo "Configuring site to skip setup wizard";
        bench --site ${WEB_DOMAIN:-intralogisticsai.online} set-config skip_setup_wizard 1;
        echo "Running ERPNext setup programmatically";
        python3 -c "import frappe; frappe.init('${WEB_DOMAIN:-intralogisticsai.online}'); frappe.connect(); from erpnext.setup.setup_wizard.setup_wizard import setup_complete; setup_complete({'language': 'en', 'country': 'United States', 'timezone': 'America/New_York', 'currency': 'USD', 'company_name': 'Roots Intralogistics', 'company_abbr': 'RL', 'email': 'admin@rootseducation.co', 'first_name': 'Administrator', 'last_name': 'User'}); frappe.db.commit()" || echo "ERPNext setup failed, but site should still work";
        echo "Building assets for ${WEB_DOMAIN:-intralogisticsai.online}";
        bench --site ${WEB_DOMAIN:-intralogisticsai.online} build;
        echo "Assets built successfully";

networks:
  frappe_network: {}

volumes:
  sites:
  logs: